Garage2.0/Controllers/MemberController.cs
#nullable disable
using Bogus;
using Garage2._0.Data;
using Garage2._0.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Garage2._0.Controllers
{
    public class MemberController : Controller
    {
        private readonly Garage2_0Context _context;
        private Faker faker = new Faker("sv");

        public MemberController(Garage2_0Context context)
        {
            _context = context;
        }

        
        public async Task<IActionResult> Index()
        {
            return View(await _context.Member.ToListAsync());
        }

        public async Task<IActionResult> Index2()
        {
            var members = await _context.Member
                .Include(m => m.Vehicles)
                .Select(m => new MemberViewModel
                {
                    Id = m.Id,
                    Age = m.Age,
                    Avatar = m.Avatar,
                    FirstName = m.FirstName,
                    LastName = m.LastName,
                    PersonNumber = m.PersonNumber,
                    NumberOfVehicles = m.Vehicles.Count()
                })
                .ToListAsync();

            return View(nameof(Index2), members);
        }




        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .Include(m => m.Vehicles)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

       
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Member member)
        {
            if (ModelState.IsValid)
            {

                bool old = member.PersonNumber.Contains('+');
                string[] words = member.PersonNumber.Split('-', '+');
                var today = DateTime.Today;
                int lastTwoDigitsOfYear = int.Parse(today.ToString("yy"));

                var age = 0;
                if (words[0].Length == 6)
                {
                    int ageTwoDigits = int.Parse(words[0].Substring(0, 2));
                    if (old)
                    {

                        if (lastTwoDigitsOfYear < ageTwoDigits)
                            age = 100 + lastTwoDigitsOfYear + 100 - ageTwoDigits;
                        else
                            age = 100 + lastTwoDigitsOfYear - ageTwoDigits;

                    }
                    else
                    {


                        if (lastTwoDigitsOfYear < ageTwoDigits)
                            age = lastTwoDigitsOfYear + 100 - ageTwoDigits;
                        else
                            age = lastTwoDigitsOfYear - ageTwoDigits;
                    }
                }
                else
                    age = today.Year - int.Parse(words[0].Substring(0, 4));

                member.Age = age;
                member.Avatar = faker.Internet.Avatar();

                _context.Add(member);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(member);
        }
       
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member.FindAsync(id);
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Member member)
        {
            if (id != member.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(member);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemberExists(member.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .FirstOrDefaultAsync(m => m.Id == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var member = await _context.Member.FindAsync(id);
            
            if (member != null)
            {
                var parkedVehicles = _context.ParkVehicle.Where(p => p.MemberId == id);

                foreach (var vehicle in parkedVehicles)
                {
                    if (vehicle.ParkingSpotId != null)
                    {

                        TempData["Success"] = $"{member.GetFullName()} currently has unpaid parking fees so can not be removed";
                        return RedirectToAction(nameof(Index));

                    }
                   
                }

                _context.Member.Remove(member);
                await _context.SaveChangesAsync();

                TempData["Success"] = $"Member has been deleted!";

            }
            return RedirectToAction(nameof(Index));
        }

        private bool MemberExists(int id)
        {
            return _context.Member.Any(e => e.Id == id);
        }

        public async Task<IActionResult> Filter(string? firstname)
        {
            var model = string.IsNullOrWhiteSpace(firstname) ?
                                   _context.Member :
                                   _context.Member.Where(m => m.FirstName.StartsWith(firstname));

            return View(nameof(Index), await model.ToListAsync());
        }
    }
}

Garage2.0/Controllers/ParkVehiclesController.cs
#nullable disable
using Garage2._0.Data;
using Garage2._0.Helpers;
using Garage2._0.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Garage2._0.Controllers
{
    public class ParkVehiclesController : Controller
    {
        private readonly Garage2_0Context _context;
        private readonly IConfiguration _configuration;
        public ParkVehiclesController(Garage2_0Context context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        public async Task<IActionResult> Filter(string? regSearch, string? colSearch, string? brandSearch, string modelSearch, int? wheelSearch, string? vehicleType)
        {
            var model = _context.ParkVehicle.Include(m => m.VehicleType).Where(m => m.RegNumber.Contains(""));

             model = string.IsNullOrWhiteSpace(regSearch) ?
                                    model :
                                    model.Include(m => m.VehicleType).Where(m => m.RegNumber.Contains(regSearch));

            model = string.IsNullOrWhiteSpace(colSearch) ?
                          model :
                          model.Include(m => m.VehicleType).Where(m => m.Color.Contains(colSearch));

            model = string.IsNullOrWhiteSpace(brandSearch) ?
                          model :
                          model.Include(m => m.VehicleType).Where(m => m.Brand.Contains(brandSearch));

            model = string.IsNullOrWhiteSpace(modelSearch) ?
                          model :
                          model.Include(m => m.VehicleType).Where(m => m.Model.Contains(modelSearch));

            model = wheelSearch == null ?
                 model :
                 model.Include(m => m.VehicleType).Where(m => m.Wheels == wheelSearch);


            model = vehicleType == null ?
                             model :
                             model.Include(m => m.VehicleType).Where(m => m.VehicleType.Name == vehicleType);

            return View(nameof(Index), await model.ToListAsync());
        }
        public async Task<IActionResult> Index2(string? sortOrder)
        {

            IQueryable<ParkVehicle> vehicles = _context.ParkVehicle.Where(v => v.ParkingSpotId != null).Include(v => v.VehicleType).Include(v => v.Parkings).Include(v => v.Member);
            List<IndexViewModel> model = new List<IndexViewModel>();
            var timeNow = DateTime.Now;
            foreach (var vehicle in vehicles)
            {

                model.Add(new IndexViewModel
                {
                    RegNumber = vehicle.RegNumber,
                    Color = vehicle.Color,
                    Brand = vehicle.Brand,
                    Model = vehicle.Model,
                    Wheels = vehicle.Wheels,
                    ParkingSpotNR = (int)vehicle.ParkingSpotId,
                    Owner = vehicle.Member.GetFullName(),
                    VehicleType = vehicle.VehicleType.Name,
                    ParkTime = (TimeSpan)(timeNow - vehicle.CheckInTime)


                });

            }
            ViewBag.MemberSortParm = sortOrder == "Member" ? "member_desc" : "Member";
            ViewBag.VehicleSortParm = String.IsNullOrEmpty(sortOrder) ? "vehicle_desc" : "";
            ViewBag.ParkingSortParm = sortOrder == "Parking Slot" ? "park_desc" : "Parking Slot";
            ViewBag.RegNumberSortParm = sortOrder == "RegNumber" ? "RegNumber_desc" : "RegNumber";
            ViewBag.ColorSortParm = sortOrder == "Color" ? "Color_desc" : "Color";
            ViewBag.BrandSortParm = sortOrder == "Brand" ? "Brand_desc" : "Brand";
            ViewBag.ModelSortParm = sortOrder == "Model" ? "Model_desc" : "Model";
            ViewBag.WheelsSortParm = sortOrder == "Wheels" ? "Wheels_desc" : "Wheels";
            ViewBag.DurationSortParm = sortOrder == "Duration" ? "Duration_desc" : "Duration";

            switch (sortOrder)
            {

                case "vehicle_desc":
                    model = model.OrderByDescending(v => v.VehicleType).ToList();
                    break;
                case "park_desc":
                    model = model.OrderByDescending(v => v.ParkingSpotNR).ToList();
                    break;
                case "Parking Slot":
                    model = model.OrderBy(v => v.ParkingSpotNR).ToList();
                    break;
                case "RegNumber":
                    model = model.OrderBy(v => v.RegNumber).ToList();
                    break;
                case "RegNumber_desc":
                    model = model.OrderByDescending(v => v.RegNumber).ToList();
                    break;
                case "Color":
                    model = model.OrderBy(v => v.Color).ToList();
                    break;
                case "Color_desc":
                    model = model.OrderByDescending(v => v.Color).ToList();
                    break;
                case "Brand":
                    model = model.OrderBy(v => v.Brand).ToList();
                    break;
                case "Brand_desc":
                    model = model.OrderByDescending(v => v.Brand).ToList();
                    break;
                case "Model":
                    model = model.OrderBy(v => v.Model).ToList();
                    break;
                case "Model_desc":
                    model = model.OrderByDescending(v => v.Model).ToList();
                    break;
                case "Wheels":
                    model = model.OrderBy(v => v.Wheels).ToList();
                    break;
                case "Wheels_desc":
                    model = model.OrderByDescending(v => v.Wheels).ToList();
                    break;
                case "Duration":
                    model = model.OrderBy(v => v.ParkTime).ToList();
                    break;
                case "Duration_desc":
                    model = model.OrderByDescending(v => v.ParkTime).ToList();
                    break;

                case "member_desc":
                    model = model.OrderByDescending(v => v.Owner).ToList();
                    break;

                case "Member":
                    model = model.OrderBy(v => v.Owner).ToList();
                    break;

                default:
                    model = model.OrderBy(v => v.VehicleType).ToList();
                    break;
            }

            return View(nameof(Index2), model);
        }
        public async Task<IActionResult> GarageSlots()
        {
            var spots = await _context.ParkingSpot.ToListAsync();

            List<GarageSlotModel> parkingSpots = new List<GarageSlotModel>(); ;

            foreach (var item in spots)
            {
                string occupancy = "";
                if (item.ParkVehicleID != null)
                    occupancy = "Taken";
                else
                    occupancy = "Open";
                parkingSpots.Add(new GarageSlotModel
                {
                    Slot = item.ParkingSpotNr,
                    Occupancy = occupancy


                });
            }

            return View(parkingSpots);

        }

        public async Task<IActionResult> Index(string searchString, string sortOrder)
        {
            ViewBag.VehicleSortParm = String.IsNullOrEmpty(sortOrder) ? "vehicle_desc" : "";
            ViewBag.ParkingSortParm = sortOrder == "Parking Slot" ? "park_desc" : "Parking Slot";
            ViewBag.RegNumberSortParm = sortOrder == "RegNumber" ? "RegNumber_desc" : "RegNumber";
            ViewBag.ColorSortParm = sortOrder == "Color" ? "Color_desc" : "Color";
            ViewBag.BrandSortParm = sortOrder == "Brand" ? "Brand_desc" : "Brand";
            ViewBag.ModelSortParm = sortOrder == "Model" ? "Model_desc" : "Model";
            ViewBag.WheelsSortParm = sortOrder == "Wheels" ? "Wheels_desc" : "Wheels";
            ViewBag.CheckInTimeSortParm = sortOrder == "Date" ? "CheckInTime_desc" : "Date";

            IQueryable<ParkVehicle> vehicles = _context.ParkVehicle.Include(v => v.VehicleType).Include(v => v.Parkings);


            if (!String.IsNullOrEmpty(searchString))
            {
                vehicles = vehicles.Where(s => s.RegNumber!.Contains(searchString));
                return View(await vehicles.ToListAsync());
            }

            switch (sortOrder)
            {
                case "vehicle_desc":
                    vehicles = vehicles.OrderByDescending(v => v.VehicleType.Name);
                    break;
               
                case "RegNumber":
                    vehicles = vehicles.OrderBy(v => v.RegNumber);
                    break;
                case "RegNumber_desc":
                    vehicles = vehicles.OrderByDescending(v => v.RegNumber);
                    break;
                case "Color":
                    vehicles = vehicles.OrderBy(v => v.Color);
                    break;
                case "Color_desc":
                    vehicles = vehicles.OrderByDescending(v => v.Color);
                    break;
                case "Brand":
                    vehicles = vehicles.OrderBy(v => v.Brand);
                    break;
                case "Brand_desc":
                    vehicles = vehicles.OrderByDescending(v => v.Brand);
                    break;
                case "Model":
                    vehicles = vehicles.OrderBy(v => v.Model);
                    break;
                case "Model_desc":
                    vehicles = vehicles.OrderByDescending(v => v.Model);
                    break;
                case "Wheels":
                    vehicles = vehicles.OrderBy(v => v.Wheels);
                    break;
                case "Wheels_desc":
                    vehicles = vehicles.OrderByDescending(v => v.Wheels);
                    break;
                case "Date":
                    vehicles = vehicles.OrderBy(v => v.CheckInTime);
                    break;

Garage2.0/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Garage2._0</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand mt-2 mt-lg-0" asp-area="" asp-controller="ParkVehicles" asp-action="Index"><img src="~/logo.svg"
            height="15"
          alt="Garage 2.0 Logo"
          loading="lazy"
/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ParkVehicles" asp-action="Index">Full List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ParkVehicles" asp-action="Index2">Parked List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ParkVehicles" asp-action="Create">Register Vehicle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ParkVehicles" asp-action="CheckInMember">Member Check-In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Create">Register Member</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="">List of Members</a>
                        </li>
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li class="nav-item">
                            <a class="dropdown-item" asp-area="" asp-controller="ParkVehicles" asp-action="AddVehicleType">Add Vehicle Type</a>
                        </li>
                        <li class="nav-item">
                            <a class="dropdown-item" asp-area="" asp-controller="ParkVehicles" asp-action="Statistics">Statistics</a>
                        </li>
                        <li class="nav-item">
                            <a class="dropdown-item" asp-area="" asp-controller="ParkVehicles" asp-action="GarageSlots">Occupancy</a>
                        </li>
                        <li class="nav-item">
                            <a class="dropdown-item" asp-area="" asp-controller="Member" asp-action="Index2">Members List</a>
                        </li>
                    </ul>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted fixed-bottom">
        <div class="container">
            &copy Group-3 (Usukhbayar, Marcus, Jesse, Ashutosh); 2022 - Garage 2.0
        </div>
    </footer>
 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>